name: app_versioning
description: >-
  Keep track of app versions and prompt users to update the app whenever there are new updates available.
version: 1.1.0
homepage: https://github.com/levin-riegner/app_versioning
repository: https://github.com/levin-riegner/app_versioning
documentation: https://github.com/levin-riegner/app_versioning
platforms:
  android:
  ios:
screenshots:
  - description: "Displays the in-app update information."
    path: doc/static/screenshot_updates.png
  - description: "Displays the version tracking values."
    path: doc/static/screenshot_tracker.png
topics:
  - app updates
  - app version
  - versioning
  - version tracker
  - version bomb

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # App package info
  package_info_plus: ^4.2.0
  # URL Launcher
  url_launcher: ^6.1.14
  # Shared Preferences
  shared_preferences: ^2.2.2
  # Firebase Remote Config
  firebase_remote_config: ^4.3.2
  # HTTP
  http: ^1.1.0
  # In-app update
  in_app_update: ^4.2.2 # Android
  upgrader: ^8.2.0 # iOS

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
